apiVersion: v1
kind: Secret
metadata:
  name: {{DJANGO_SECRET_NAME}}
  namespace: {{NAMESPACE}}
type: Opaque
stringData:
  django-secret-key: "{{DJANGO_SECRET_KEY}}"
  ingest-api-token: "{{INGEST_API_TOKEN}}"
