[base]
name = .
coverage_dir = {env:COVERAGE_REPORT_DIR:coverage_reports}

[tox]
minversion = 4.0
envlist = py313, lint

[testenv]
passenv =
    CI_PIPELINE_ID
    DJANGO_*
    POSTGRES_*
    UV_*
skip_install = true
setenv =
    UV_PROJECT_ENVIRONMENT = {envdir}
    RUFF_CACHE_DIR = {envtmpdir}/ruff-cache
allowlist_externals = uv
commands_pre =
    uv sync --locked --no-default-groups --group test --python {envpython}
commands =
    coverage run --source {[base]name} --data-file={[base]coverage_dir}/.coverage --omit api/tests/*,api/migrations/*,api/schema.py,config/*,manage.py manage.py test api/tests --verbosity 2 {posargs}
    coverage report --data-file={[base]coverage_dir}/.coverage -m --skip-covered
    coverage xml --data-file={[base]coverage_dir}/.coverage -o {[base]coverage_dir}/coverage.xml

[testenv:lint]
commands_pre =
    uv sync --locked --no-default-groups --group lint --python {envpython}
commands =
    ruff format --diff {[base]name}
    ruff check {[base]name}

[testenv:format]
commands_pre =
    uv sync --locked --no-default-groups --group lint --python {envpython}
commands =
    ruff format {[base]name}
    ruff check --fix {[base]name}

[testenv:types]
commands_pre =
    uv sync --locked --no-default-groups --group types --python {envpython}
commands =
    pyright {[base]name}
