# Generated by Django 4.2.3 on 2026-03-02 11:46

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0000_enable_pg_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_type', models.CharField(choices=[('accepted', 'Accepted'), ('synonym', 'Synonym')], max_length=16)),
                ('name_raw', models.CharField(max_length=512)),
                ('canonical_norm', models.CharField(db_index=True, max_length=512)),
                ('genus_norm', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('epithet_norm', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('genus_prefix2', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('genus_prefix3', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('canon_prefix3', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'name_index',
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aphia_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(db_index=True, max_length=512)),
                ('rank', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(db_index=True, max_length=64)),
                ('worms_modified', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('cached_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('access_count', models.BigIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.taxon')),
                ('valid_taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synonym_children', to='api.taxon')),
            ],
            options={
                'db_table': 'taxa',
            },
        ),
        migrations.CreateModel(
            name='Vernacular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=512)),
                ('language_code', models.CharField(db_index=True, max_length=8)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vernaculars', to='api.taxon')),
            ],
            options={
                'db_table': 'vernaculars',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False)),
                ('rank_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'ranks',
                'indexes': [models.Index(fields=['rank_id'], name='rank_id_idx'), models.Index(fields=['name'], name='rank_name_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='rank',
            constraint=models.UniqueConstraint(fields=('rank_id', 'name'), name='uq_rank'),
        ),
        migrations.AddField(
            model_name='nameindex',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_index', to='api.taxon'),
        ),
        migrations.AddIndex(
            model_name='vernacular',
            index=models.Index(fields=['taxon'], name='vern_taxon_idx'),
        ),
        migrations.AddIndex(
            model_name='vernacular',
            index=models.Index(fields=['taxon', 'language_code'], name='vern_taxon_lang_idx'),
        ),
        migrations.AddIndex(
            model_name='vernacular',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='vern_name_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='vernacular',
            constraint=models.UniqueConstraint(fields=('taxon', 'name', 'language_code'), name='uq_vern'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['rank', 'status'], name='taxa_rank_status_idx'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['scientific_name'], name='taxa_scientific_name_idx'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['parent'], name='taxa_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['valid_taxon'], name='taxa_valid_taxon_idx'),
        ),
        migrations.AddIndex(
            model_name='taxon',
            index=models.Index(fields=['cached_at'], name='taxa_cached_at_idx'),
        ),
        migrations.AddIndex(
            model_name='nameindex',
            index=models.Index(fields=['genus_norm', 'epithet_norm'], name='nameidx_genus_epithet_idx'),
        ),
        migrations.AddIndex(
            model_name='nameindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['canonical_norm'], name='nameidx_canon_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='nameindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['genus_norm'], name='nameidx_genus_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='nameindex',
            constraint=models.UniqueConstraint(fields=('taxon', 'name_type', 'name_raw'), name='uq_nameindex'),
        ),
    ]
