# Default values for worms-cache-api.

# bodc-nginx ingress configuration.
ingress:
  enabled: false

# WORMS Cache API Django configuration.
# ====================================

# api-deployment configuration.
api:
  workers: 1
  image:
    repository: ghcr.io/paidiver/worms-cache
    tag: latest
    imagePullSecret: worms-cache-api-ghcr-pull-secret
    pullPolicy: Always
  env:
    djangoCorsAllowedOrigins: "https://paidiver.github.io"
    djangoCorsAllowAll: "0"
    djangoSecretKey:
      secretName: worms-cache-api-django-secret
    ingestApiToken:
      secretName: worms-cache-api-django-secret
  resources:
    requests:
      cpu: "20m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"

# api-migrate-job configuration.
migrateJob:
  enabled: true
  image:
    repository: ghcr.io/paidiver/worms-cache
    tag: latest
    pullPolicy: Always
    imagePullSecret: worms-cache-api-ghcr-pull-secret

# refresh-cron configuration.
refreshCron:
  enabled: true

# taxamatch-deployment configuration.
taxamatch:
  resources:
    requests:
      cpu: "20m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
