FROM ruby:2.6-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends build-essential && \
    rm -rf /var/lib/apt/lists/*

COPY taxamatch_service/Gemfile taxamatch_service/Gemfile.lock* /app/
RUN gem install bundler -v 2.4.22 && bundle _2.4.22_ install

COPY taxamatch_service/. /app

ENV RACK_ENV=production
EXPOSE 8080

CMD ["bundle", "exec", "puma", "-C", "puma.rb", "config.ru"]
