--
-- PostgreSQL database dump
--

\restrict 1baVaF1NVAe1VkrJIcjNn0Rejd5uqypGbKghqqPeVKHgW102H4QbroHW6xNhAuO

-- Dumped from database version 18.6 (Debian 18.6-1.pgdg13+2)
-- Dumped by pg_dump version 18.6 (Debian 18.6-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


--
-- Name: EXTENSION pg_trgm; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_trgm IS 'text similarity measurement and index searching based on trigrams';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_refreshstate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_refreshstate (
    name character varying(32) NOT NULL,
    last_success_at timestamp with time zone,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    status character varying(16) NOT NULL,
    failed_ids jsonb NOT NULL
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: name_index; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.name_index (
    id bigint NOT NULL,
    name_type character varying(16) NOT NULL,
    name_raw character varying(512) NOT NULL,
    canonical_norm character varying(512) NOT NULL,
    genus_norm character varying(128),
    epithet_norm character varying(128),
    genus_prefix2 character varying(2),
    genus_prefix3 character varying(3),
    canon_prefix3 character varying(3),
    taxon_id integer NOT NULL
);


--
-- Name: name_index_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.name_index ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.name_index_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ranks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ranks (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(64) NOT NULL,
    rank_id integer NOT NULL,
    CONSTRAINT ranks_rank_id_check CHECK ((rank_id >= 0))
);


--
-- Name: taxa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.taxa (
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    aphia_id integer NOT NULL,
    scientific_name character varying(512) NOT NULL,
    rank character varying(64) NOT NULL,
    status character varying(64) NOT NULL,
    worms_modified timestamp with time zone,
    source_url character varying(200),
    cached_at timestamp with time zone NOT NULL,
    last_accessed_at timestamp with time zone,
    access_count bigint NOT NULL,
    parent_id integer,
    valid_taxon_id integer,
    CONSTRAINT taxa_aphia_id_check CHECK ((aphia_id >= 0))
);


--
-- Name: vernaculars; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.vernaculars (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name character varying(512) NOT NULL,
    language_code character varying(8) NOT NULL,
    taxon_id integer NOT NULL
);


--
-- Name: vernaculars_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.vernaculars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vernaculars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_refreshstate api_refreshstate_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_refreshstate
    ADD CONSTRAINT api_refreshstate_pkey PRIMARY KEY (name);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: name_index name_index_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.name_index
    ADD CONSTRAINT name_index_pkey PRIMARY KEY (id);


--
-- Name: ranks ranks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ranks
    ADD CONSTRAINT ranks_pkey PRIMARY KEY (name);


--
-- Name: taxa taxa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.taxa
    ADD CONSTRAINT taxa_pkey PRIMARY KEY (aphia_id);


--
-- Name: name_index uq_nameindex; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.name_index
    ADD CONSTRAINT uq_nameindex UNIQUE (taxon_id, name_type, name_raw);


--
-- Name: ranks uq_rank; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ranks
    ADD CONSTRAINT uq_rank UNIQUE (rank_id, name);


--
-- Name: vernaculars uq_vern; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vernaculars
    ADD CONSTRAINT uq_vern UNIQUE (taxon_id, name, language_code);


--
-- Name: vernaculars vernaculars_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vernaculars
    ADD CONSTRAINT vernaculars_pkey PRIMARY KEY (id);


--
-- Name: api_refreshstate_name_87a06445_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_refreshstate_name_87a06445_like ON public.api_refreshstate USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: name_index_canon_prefix3_1cf9deb2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index_canon_prefix3_1cf9deb2 ON public.name_index USING btree (canon_prefix3);


--
-- Name: name_index_canon_prefix3_1cf9deb2_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index_canon_prefix3_1cf9deb2_like ON public.name_index USING btree (canon_prefix3 varchar_pattern_ops);


--
-- Name: name_index_canonical_norm_b595cb52; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index_canonical_norm_b595cb52 ON public.name_index USING btree (canonical_norm);


--
-- Name: name_index_canonical_norm_b595cb52_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index_canonical_norm_b595cb52_like ON public.name_index USING btree (canonical_norm varchar_pattern_ops);


--
-- Name: name_index_epithet_norm_fb8c4619; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index_epithet_norm_fb8c4619 ON public.name_index USING btree (epithet_norm);


--
-- Name: name_index_epithet_norm_fb8c4619_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index_epithet_norm_fb8c4619_like ON public.name_index USING btree (epithet_norm varchar_pattern_ops);


--
-- Name: name_index_genus_norm_98f1cde8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index_genus_norm_98f1cde8 ON public.name_index USING btree (genus_norm);


--
-- Name: name_index_genus_norm_98f1cde8_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index_genus_norm_98f1cde8_like ON public.name_index USING btree (genus_norm varchar_pattern_ops);


--
-- Name: name_index_genus_prefix2_cf64da3a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index_genus_prefix2_cf64da3a ON public.name_index USING btree (genus_prefix2);


--
-- Name: name_index_genus_prefix2_cf64da3a_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index_genus_prefix2_cf64da3a_like ON public.name_index USING btree (genus_prefix2 varchar_pattern_ops);


--
-- Name: name_index_genus_prefix3_1cdcae55; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index_genus_prefix3_1cdcae55 ON public.name_index USING btree (genus_prefix3);


--
-- Name: name_index_genus_prefix3_1cdcae55_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index_genus_prefix3_1cdcae55_like ON public.name_index USING btree (genus_prefix3 varchar_pattern_ops);


--
-- Name: name_index_taxon_id_15fd61e7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX name_index_taxon_id_15fd61e7 ON public.name_index USING btree (taxon_id);


--
-- Name: nameidx_canon_trgm_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nameidx_canon_trgm_gin ON public.name_index USING gin (canonical_norm public.gin_trgm_ops);


--
-- Name: nameidx_genus_epithet_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nameidx_genus_epithet_idx ON public.name_index USING btree (genus_norm, epithet_norm);


--
-- Name: nameidx_genus_trgm_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX nameidx_genus_trgm_gin ON public.name_index USING gin (genus_norm public.gin_trgm_ops);


--
-- Name: rank_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rank_id_idx ON public.ranks USING btree (rank_id);


--
-- Name: rank_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX rank_name_idx ON public.ranks USING btree (name);


--
-- Name: ranks_name_e75b2431_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ranks_name_e75b2431_like ON public.ranks USING btree (name varchar_pattern_ops);


--
-- Name: taxa_cached_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxa_cached_at_idx ON public.taxa USING btree (cached_at);


--
-- Name: taxa_last_accessed_at_047716f1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxa_last_accessed_at_047716f1 ON public.taxa USING btree (last_accessed_at);


--
-- Name: taxa_parent_id_3bdbb46d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxa_parent_id_3bdbb46d ON public.taxa USING btree (parent_id);


--
-- Name: taxa_parent_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxa_parent_idx ON public.taxa USING btree (parent_id);


--
-- Name: taxa_rank_3c995505; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxa_rank_3c995505 ON public.taxa USING btree (rank);


--
-- Name: taxa_rank_3c995505_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxa_rank_3c995505_like ON public.taxa USING btree (rank varchar_pattern_ops);


--
-- Name: taxa_rank_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxa_rank_status_idx ON public.taxa USING btree (rank, status);


--
-- Name: taxa_scientific_name_d6c0f7e5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxa_scientific_name_d6c0f7e5 ON public.taxa USING btree (scientific_name);


--
-- Name: taxa_scientific_name_d6c0f7e5_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxa_scientific_name_d6c0f7e5_like ON public.taxa USING btree (scientific_name varchar_pattern_ops);


--
-- Name: taxa_scientific_name_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxa_scientific_name_idx ON public.taxa USING btree (scientific_name);


--
-- Name: taxa_status_a0e36b3f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxa_status_a0e36b3f ON public.taxa USING btree (status);


--
-- Name: taxa_status_a0e36b3f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxa_status_a0e36b3f_like ON public.taxa USING btree (status varchar_pattern_ops);


--
-- Name: taxa_valid_taxon_id_31d7adb3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxa_valid_taxon_id_31d7adb3 ON public.taxa USING btree (valid_taxon_id);


--
-- Name: taxa_valid_taxon_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX taxa_valid_taxon_idx ON public.taxa USING btree (valid_taxon_id);


--
-- Name: vern_name_trgm_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vern_name_trgm_gin ON public.vernaculars USING gin (name public.gin_trgm_ops);


--
-- Name: vern_taxon_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vern_taxon_idx ON public.vernaculars USING btree (taxon_id);


--
-- Name: vern_taxon_lang_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vern_taxon_lang_idx ON public.vernaculars USING btree (taxon_id, language_code);


--
-- Name: vernaculars_language_code_b0dbd09b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vernaculars_language_code_b0dbd09b ON public.vernaculars USING btree (language_code);


--
-- Name: vernaculars_language_code_b0dbd09b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vernaculars_language_code_b0dbd09b_like ON public.vernaculars USING btree (language_code varchar_pattern_ops);


--
-- Name: vernaculars_taxon_id_39ad9304; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX vernaculars_taxon_id_39ad9304 ON public.vernaculars USING btree (taxon_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: name_index name_index_taxon_id_15fd61e7_fk_taxa_aphia_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.name_index
    ADD CONSTRAINT name_index_taxon_id_15fd61e7_fk_taxa_aphia_id FOREIGN KEY (taxon_id) REFERENCES public.taxa(aphia_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: taxa taxa_parent_id_3bdbb46d_fk_taxa_aphia_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.taxa
    ADD CONSTRAINT taxa_parent_id_3bdbb46d_fk_taxa_aphia_id FOREIGN KEY (parent_id) REFERENCES public.taxa(aphia_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: taxa taxa_valid_taxon_id_31d7adb3_fk_taxa_aphia_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.taxa
    ADD CONSTRAINT taxa_valid_taxon_id_31d7adb3_fk_taxa_aphia_id FOREIGN KEY (valid_taxon_id) REFERENCES public.taxa(aphia_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: vernaculars vernaculars_taxon_id_39ad9304_fk_taxa_aphia_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.vernaculars
    ADD CONSTRAINT vernaculars_taxon_id_39ad9304_fk_taxa_aphia_id FOREIGN KEY (taxon_id) REFERENCES public.taxa(aphia_id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 1baVaF1NVAe1VkrJIcjNn0Rejd5uqypGbKghqqPeVKHgW102H4QbroHW6xNhAuO

