apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: primary
    app.kubernetes.io/instance: {{RELEASE_NAME}}
    app.kubernetes.io/name: postgresql
  name: {{POSTGRES_PVC_NAME}}
  namespace: {{NAMESPACE}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{POSTGRES_PVC_SIZE}}
  storageClassName: csi-cinder
  # storageClassName: scale-nocacuk-bodc2
  volumeMode: Filesystem
