apiVersion: v1
kind: Secret
metadata:
  name: {{POSTGRES_SECRET_NAME}}
  namespace: {{NAMESPACE}}
type: Opaque
stringData:
  password: "{{POSTGRES_PASSWORD}}"
  postgres-password: "{{POSTGRES_SUPERUSER_PASSWORD}}"
