apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "worms-cache-api.fullname" . }}
  labels:
    {{- include "worms-cache-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: {{ .Values.api.componentName }}
      {{- include "worms-cache-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: {{ .Values.api.componentName }}
        {{- include "worms-cache-api.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-postgres
          image: bitnami/postgresql@{{ .Values.postgresql.image.digest }}
          command:
            - sh
            - -ec
            - |
              echo "Waiting for PostgreSQL..."
              until pg_isready \
                -h $POSTGRES_HOST \
                -p $POSTGRES_PORT \
                -U $POSTGRES_USER; do
                sleep 2
              done
          securityContext:
            {{- toYaml .Values.api.initContainer.securityContext | nindent 12 }}
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          env: {{ include "api.postgresEnv" . | nindent 12 }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.env.djangoSecretKey.secretName }}
                  key: {{ .Values.api.env.djangoSecretKey.secretKey }}
            - name: DJANGO_DEBUG
              value: "{{ .Values.api.env.djangoDebug }}"
            - name: DJANGO_ALLOWED_HOSTS
              value: localhost,127.0.0.1,0.0.0.0,{{ .Values.ingress.host }}
            - name: TAXAMATCH_URL
              value: {{ default (printf "http://%s-taxamatch-service:8080" .Release.Name) .Values.api.env.taxamatchUrl | quote }}
            - name: WORMS_API_BASE_URL
              value: "{{ .Values.api.env.wormsApiBaseUrl }}"
            - name: INGEST_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.api.env.ingestApiToken.secretName }}
                  key: {{ .Values.api.env.ingestApiToken.secretKey }}
            {{ include "api.postgresEnv" . | nindent 12 }}
          command:
            - sh
            - -c
            - |
              poetry run gunicorn config.wsgi:application -w {{ .Values.api.workers }} -b 0.0.0.0:{{ .Values.api.port }} --timeout {{ .Values.api.timeout }}
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
      imagePullSecrets:
        - name: {{ .Values.api.image.imagePullSecret }}
