# templates/purge-volume-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-purge-volume
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: purge
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Purging volume..."
              rm -rf /data/*
          volumeMounts:
            - name: postgres-data
              mountPath: /data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: {{ .Values.postgresql.pvc.name }}
