replicaCount: 1

ingress:
  host: worms-cache-dev.paidiver.site
  path: ""
  tls:
    - secretName: letsencrypt-worms-cache
      hosts:
        - worms-cache-dev.paidiver.site

api:
  workers: 1

postgresql:
  primary:
    persistence:
      enabled: true
      size: 2Gi
    resources:
      limits:
        memory: 1Gi
