source "https://rubygems.org"

gem "sinatra", "~> 1.4.8"
gem "rack", "~> 1.6"
gem "puma", "~> 4.3"
gem "json", "~> 1.8"
gem "taxamatch_rb", "~> 1.0"

group :development do
  gem "sinatra-contrib", require: false
end

group :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
end
