apiVersion: v2
name: api
description: A database and API for imagery metadata and worms-cache
type: application
version: 0.0.2-debug.20260303133040
appVersion: 0.0.2-debug.20260303133040
maintainers:
  - name: tobfer
    email: tobias.ferreira@noc.ac.uk
    url: bodc.ac.uk
dependencies:
  - name: postgresql
    version: 18.2.4
    repository: https://charts.bitnami.com/bitnami
