apiVersion: v2
name: api
description: A database and API for imagery metadata and worms-cache
type: application
version: 0.0.6
appVersion: 0.0.6
maintainers:
  - name: tobfer
    email: tobias.ferreira@noc.ac.uk
    url: bodc.ac.uk
