apiVersion: v1
kind: Secret
metadata:
  name: {{GHCR_SECRET_NAME}}
  namespace: {{NAMESPACE}}
type: kubernetes.io/docker-registry
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "{{GHCR_USERNAME}}",
          "password": "{{GHCR_TOKEN}}",
        }
      }
    }
