name: Build Docker Image

on:
  pull_request:
    branches: [main]

jobs:
  build-api:
    permissions:
      contents: read
    uses: paidiver/brokerage-service/.github/workflows/reusable-docker-build.yml@main
