name: CI

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    permissions:
      contents: read
    uses: paidiver/brokerage-service/.github/workflows/reusable-python-django-ci.yml@main
    with:
      postgres_database: worms-cache-db
